# Generated by Django 3.2.6 on 2021-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('est', models.IntegerField()),
                ('olympics', models.BooleanField()),
                ('skaters', models.ManyToManyField(blank=True, related_name='team', to='skaters.Skater')),
            ],
        ),
    ]
